version: '2'
services:

  producer-service:
    hostname: docker-producer-service-1
    container_name: docker-producer-service-1
    image: com.roek5803.spring-boot-kafka-example/producer-service:1.0-SNAPSHOT
    ports:
      - "8080:8080"

  consumer-service:
    hostname: docker-consumer-service-1
    container_name: docker-consumer-service-1
    image: com.roek5803.spring-boot-kafka-example/consumer-service:1.0-SNAPSHOT
    ports:
      - "8081:8080"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-1.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      HOSTNAME_COMMAND: "echo $$(hostname)"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_PORT: 9092
      BROKER_ID_COMMAND: "docker inspect --format '{{ .Name }}' $$(hostname) | awk -F_ '{ printf $$NF }'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "message:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock